# Sidebar navigation

- label: 'Introdução ao projeto'
  link: '/'
- label: 'Corretoras para comprar BTC'
  link: '/corretoras'
- label: 'Artigos'
  items:
    - label: 'Artigo Hold BTC 100'
      link: '/articles/hold-btc'
    - label: 'Artigo sobre Lightning Network'
      link: '/articles/lightning-network'
- label: 'Vídeos interessantes'
  items:
    - label: 'Criando COLD Wallet'
    - link: 'https://www.youtube.com/watch?v=2Eot1xn9Zyo'
- label: 'Projeto HOLD BTC'
  items:
    - label: 'Grupo no Telegram'
      link: 'https://t.me/holdbtc100'
    - label: 'Pílula Laranja'
      link: 'https://docs.google.com/spreadsheets/d/1_xIm_z5HMALLRcg_satIbwxjUvj7EtcryyrwDk2-cFQ/edit#gid=0'
    - label: 'Tabela HOLD BTC 100'
      link: 'https://docs.google.com/spreadsheets/d/1yvh4m1uRpnCtJPfSWlaxZCBGlufrAdXS-YFdhhUeGWU/edit?usp=drivesdk'
    - label: 'Nossos links'
      link: 'http://linktr.ee/euusobtc'
    - label: 'Grupo no Telegram'
      link: 'https://t.me/holdbtc100'
    - label: 'Grupo no Telegram'
      link: 'https://t.me/holdbtc100'
