# Sidebar navigation

- label: 'Introdução ao projeto'
  link: '/'
- label: 'Iniciando nas compras'
  link: '/getting-started'
- label: 'Projeto HOLD BTC'
  items:
    - label: 'Grupo no Telegram'
      link: 'https://t.me/holdbtc100'
