# Sidebar navigation

- label: 'Introdução ao projeto'
  link: '/'
- label: 'Corretoras para comprar BTC'
  link: '/corretoras'
- label: 'Artigos'
  items:
    - label: 'Artigo Hold BTC 100'
      link: '/articles/hold-btc'
    - label: 'Artigo sobre Lightning Network'
      link: '/articles/lightning-network'
- label: 'Projeto HOLD BTC'
  items:
    - label: 'Grupo no Telegram'
      link: 'https://t.me/holdbtc100'
